# Generated by Django 4.0.4 on 2022-04-23 11:09

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=8)),
                ('ico', models.CharField(max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CurrenciesRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('first_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_currency', to='app.currencies')),
                ('second_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_currency', to='app.currencies')),
            ],
            options={
                'verbose_name': 'Котировка',
                'verbose_name_plural': 'Котировки',
                'ordering': ['first_currency'],
            },
        ),
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.DecimalField(decimal_places=4, default=0.0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Категория новости',
                'verbose_name_plural': 'Категории новостей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Источник новости',
                'verbose_name_plural': 'Источники новостей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.currencies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.extendeduser')),
            ],
            options={
                'verbose_name': 'Акция пользователя',
                'verbose_name_plural': 'Акции пользователей',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type_price_markup', models.CharField(choices=[('%', 'в процентах'), ('.', 'абсолютное значение')], max_length=3)),
                ('procent_markup', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('absolute_markup', models.DecimalField(decimal_places=4, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.ManyToManyField(to='app.currenciesrates')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('short_text', models.CharField(max_length=512)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.newscategories')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sources')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='BuySellOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_balance_operation', models.CharField(choices=[('Покупка', 'Покупка'), ('Продажа', 'Продажа')], max_length=16)),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.ManyToManyField(to='app.currencies')),
                ('user', models.ManyToManyField(to='app.extendeduser')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_balance_operation', models.CharField(choices=[('Пополнение', 'Пополнение'), ('Снятие', 'Снятие')], max_length=16)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ManyToManyField(to='app.extendeduser')),
            ],
        ),
    ]
