# Generated by Django 4.0.4 on 2022-04-23 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balanceoperations',
            options={'ordering': ['date'], 'verbose_name': 'Операция с балансом', 'verbose_name_plural': 'Операции с балансом'},
        ),
        migrations.AlterModelOptions(
            name='buyselloperations',
            options={'ordering': ['date'], 'verbose_name': 'Операция покупки-продажи', 'verbose_name_plural': 'Операции покупки-продажи'},
        ),
        migrations.AlterModelOptions(
            name='extendeduser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='buyselloperations',
            old_name='type_balance_operation',
            new_name='type_buy_sell_operation',
        ),
        migrations.AddField(
            model_name='buyselloperations',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='ico',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
