# Generated by Django 4.0.4 on 2022-04-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_balanceoperations_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproperties',
            options={'verbose_name': 'Валюта пользователя', 'verbose_name_plural': 'Валюты пользователей'},
        ),
    ]
