# Generated by Django 4.0.4 on 2022-04-23 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userproperties_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyselloperations',
            name='user',
        ),
        migrations.AddField(
            model_name='buyselloperations',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.extendeduser'),
        ),
    ]
